"""empty message

Revision ID: 12bf75c80928
Revises: 
Create Date: 2022-08-04 11:51:13.324621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bf75c80928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_comun', sa.String(length=250), nullable=True),
    sa.Column('nombre_cientifico', sa.String(length=250), nullable=True),
    sa.Column('riego', sa.String(length=900), nullable=True),
    sa.Column('luz', sa.String(length=250), nullable=True),
    sa.Column('poda', sa.String(length=250), nullable=True),
    sa.Column('abono', sa.String(length=250), nullable=True),
    sa.Column('trasplante', sa.String(length=250), nullable=True),
    sa.Column('tipo', sa.String(length=250), nullable=True),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('periodo_verano', sa.Integer(), nullable=True),
    sa.Column('periodo_invierno', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_cientifico')
    )
    op.create_table('plagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('sintomas', sa.String(length=250), nullable=False),
    sa.Column('prevencion', sa.String(length=250), nullable=False),
    sa.Column('tratamiento', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('riego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=80), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('intervalo', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('second_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('info_plant_id', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=250), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['info_plant_id'], ['info_plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant')
    op.drop_table('user')
    op.drop_table('riego')
    op.drop_table('plagas')
    op.drop_table('info_plant')
    # ### end Alembic commands ###
