"""empty message

Revision ID: 1413547f6ee1
Revises: 
Create Date: 2022-06-13 12:19:44.777128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1413547f6ee1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('sintoms', sa.String(length=250), nullable=False),
    sa.Column('prevention', sa.String(length=250), nullable=False),
    sa.Column('treatment', sa.String(length=250), nullable=False),
    sa.Column('test', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plagas')
    # ### end Alembic commands ###
