"""empty message

Revision ID: 2579f11daece
Revises: 960ffe3c84d9
Create Date: 2022-06-25 09:11:39.733731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2579f11daece'
down_revision = '960ffe3c84d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('misplantas', sa.Column('infoplant', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'misplantas', 'infoplant', ['infoplant'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'misplantas', type_='foreignkey')
    op.drop_column('misplantas', 'infoplant')
    # ### end Alembic commands ###
