"""empty message

Revision ID: 353d1f3d4029
Revises: e977297e0c64
Create Date: 2022-06-22 17:26:43.808405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353d1f3d4029'
down_revision = 'e977297e0c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info_plant', 'riego',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=900),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info_plant', 'riego',
               existing_type=sa.String(length=900),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###
