"""empty message

Revision ID: 43e09bd5fdb5
Revises: 2579f11daece
Create Date: 2022-06-25 09:15:20.223371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e09bd5fdb5'
down_revision = '2579f11daece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('misplantas_infoplant_fkey', 'misplantas', type_='foreignkey')
    op.drop_column('misplantas', 'infoplant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('misplantas', sa.Column('infoplant', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('misplantas_infoplant_fkey', 'misplantas', 'infoplant', ['infoplant'], ['id'])
    # ### end Alembic commands ###
