"""empty message

Revision ID: 44bbd2db69ae
Revises: 1413547f6ee1
Create Date: 2022-06-13 16:10:55.774260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bbd2db69ae'
down_revision = '1413547f6ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plagas', sa.Column('nombre', sa.String(length=250), nullable=False))
    op.add_column('plagas', sa.Column('prevencion', sa.String(length=250), nullable=False))
    op.add_column('plagas', sa.Column('sintomas', sa.String(length=250), nullable=False))
    op.add_column('plagas', sa.Column('tratamiento', sa.String(length=250), nullable=False))
    op.drop_constraint('plagas_name_key', 'plagas', type_='unique')
    op.create_unique_constraint(None, 'plagas', ['nombre'])
    op.drop_column('plagas', 'prevention')
    op.drop_column('plagas', 'test')
    op.drop_column('plagas', 'treatment')
    op.drop_column('plagas', 'name')
    op.drop_column('plagas', 'sintoms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plagas', sa.Column('sintoms', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('plagas', sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('plagas', sa.Column('treatment', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('plagas', sa.Column('test', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('plagas', sa.Column('prevention', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'plagas', type_='unique')
    op.create_unique_constraint('plagas_name_key', 'plagas', ['name'])
    op.drop_column('plagas', 'tratamiento')
    op.drop_column('plagas', 'sintomas')
    op.drop_column('plagas', 'prevencion')
    op.drop_column('plagas', 'nombre')
    # ### end Alembic commands ###
