"""empty message

Revision ID: 5419eb444edc
Revises: c843c0737c95
Create Date: 2022-06-15 18:21:13.376138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5419eb444edc'
down_revision = 'c843c0737c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
