"""empty message

Revision ID: 960ffe3c84d9
Revises: a2ed346e82f3
Create Date: 2022-06-25 09:08:51.848679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960ffe3c84d9'
down_revision = 'a2ed346e82f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('misplantas_user_fkey', 'misplantas', type_='foreignkey')
    op.drop_column('misplantas', 'user')
    op.add_column('user', sa.Column('misplantas', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'misplantas', ['misplantas'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'misplantas')
    op.add_column('misplantas', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('misplantas_user_fkey', 'misplantas', 'user', ['user'], ['id'])
    # ### end Alembic commands ###
