"""empty message

Revision ID: a2ed346e82f3
Revises: 
Create Date: 2022-06-25 09:01:12.556741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ed346e82f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('sintomas', sa.String(length=250), nullable=False),
    sa.Column('prevencion', sa.String(length=250), nullable=False),
    sa.Column('tratamiento', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('second_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('misplantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infoplant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_comun', sa.String(length=250), nullable=True),
    sa.Column('nombre_cientifico', sa.String(length=250), nullable=True),
    sa.Column('riego', sa.String(length=900), nullable=True),
    sa.Column('luz', sa.String(length=250), nullable=True),
    sa.Column('poda', sa.String(length=250), nullable=True),
    sa.Column('abono', sa.String(length=250), nullable=True),
    sa.Column('trasplante', sa.String(length=250), nullable=True),
    sa.Column('tipo', sa.String(length=250), nullable=True),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('periodo_verano', sa.Integer(), nullable=True),
    sa.Column('periodo_invierno', sa.Integer(), nullable=True),
    sa.Column('misplantas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['misplantas'], ['misplantas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_cientifico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infoplant')
    op.drop_table('misplantas')
    op.drop_table('user')
    op.drop_table('plagas')
    # ### end Alembic commands ###
