"""empty message

Revision ID: a49a96e047b1
Revises: 
Create Date: 2022-06-19 21:54:21.519916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49a96e047b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_comun', sa.String(length=250), nullable=True),
    sa.Column('nombre_cientifico', sa.String(length=250), nullable=True),
    sa.Column('riego', sa.String(length=250), nullable=True),
    sa.Column('luz', sa.String(length=250), nullable=True),
    sa.Column('poda', sa.String(length=250), nullable=True),
    sa.Column('abono', sa.String(length=250), nullable=True),
    sa.Column('trasplante', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_cientifico')
    )
    op.create_table('plagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('sintomas', sa.String(length=250), nullable=False),
    sa.Column('prevencion', sa.String(length=250), nullable=False),
    sa.Column('tratamiento', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('plagas')
    op.drop_table('info_plant')
    # ### end Alembic commands ###
