"""empty message

Revision ID: c843c0737c95
Revises: 
Create Date: 2022-06-13 19:08:16.162290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c843c0737c95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_comun', sa.String(length=250), nullable=True),
    sa.Column('nombre_cientifico', sa.String(length=250), nullable=True),
    sa.Column('riego', sa.String(length=250), nullable=True),
    sa.Column('luz', sa.String(length=250), nullable=True),
    sa.Column('poda', sa.String(length=250), nullable=True),
    sa.Column('abono', sa.String(length=250), nullable=True),
    sa.Column('trasplante', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_cientifico')
    )
    op.create_table('plagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('sintomas', sa.String(length=250), nullable=False),
    sa.Column('prevencion', sa.String(length=250), nullable=False),
    sa.Column('tratamiento', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plagas')
    op.drop_table('info_plant')
    # ### end Alembic commands ###
