"""empty message

Revision ID: c8654cb344b2
Revises: 56be6b8252b3
Create Date: 2022-06-13 16:05:03.576749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8654cb344b2'
down_revision = '56be6b8252b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_plant', sa.Column('trasplante', sa.String(length=250), nullable=True))
    op.drop_column('info_plant', 'transplante')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_plant', sa.Column('transplante', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('info_plant', 'trasplante')
    # ### end Alembic commands ###
