"""empty message

Revision ID: cf042ce223d2
Revises: d3e6bcb61d69
Create Date: 2022-06-19 22:28:40.120667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf042ce223d2'
down_revision = 'd3e6bcb61d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_second_name_key', 'user', type_='unique')
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.create_unique_constraint('user_second_name_key', 'user', ['second_name'])
    # ### end Alembic commands ###
