"""empty message

Revision ID: d3e6bcb61d69
Revises: a49a96e047b1
Create Date: 2022-06-19 22:07:45.214000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e6bcb61d69'
down_revision = 'a49a96e047b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('second_name', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['second_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'second_name')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
